let suggestion = [
    "Login form in html and css",
    "website in html and css",
    "portfolio in html and css",
    "e-commerce  in html and css",
    "landingpage  in html and css",
    "developer",
    "designer",
    "game-developer",
    "app-developer",
    "jamaldeen",
    "miss-happiness",
    "oga-kimmy",
    "frontend developer",
    "backend developer",
    "python",
    "machine language",
    "How create a search bar",
    "css responsiveness",
    "brother buddu",
    "toyman",
    "fantastic",
];